import { TeamMember } from "../types/teamMembers";
export const mockTeamMembers: TeamMember[] = [
  {
    id: "1",
    firstName: "Michael",
    lastName: "Johnson",
    email: "michael.johnson@example.com",
    position: "Senior Project Manager",
    phone: "+1 (555) 123-4567",
    userType: "admin",
    role: "manager",
    status: "registered",
    avatarUrl: "https://randomuser.me/api/portraits/men/32.jpg",
    department: "Project Management",
    hireDate: "March 15, 2019",
    lastActive: "2 hours ago",
  },
  {
    id: "2",
    firstName: "Sarah",
    lastName: "Williams",
    email: "sarah.williams@example.com",
    position: "HR Specialist",
    phone: "+1 (555) 987-6543",
    userType: "user",
    role: "hr",
    status: "registered",
    avatarUrl: "https://randomuser.me/api/portraits/women/44.jpg",
    department: "Human Resources",
    hireDate: "June 22, 2020",
    lastActive: "30 minutes ago",
  },
  {
    id: "3",
    firstName: "David",
    lastName: "Smith",
    email: "david.smith@example.com",
    position: "Software Engineer",
    phone: "+1 (555) 234-5678",
    userType: "user",
    role: "developer",
    status: "registered",
    avatarUrl: "https://randomuser.me/api/portraits/men/45.jpg",
    department: "Engineering",
    hireDate: "January 5, 2021",
    lastActive: "5 minutes ago",
  },
  {
    id: "4",
    firstName: "Emily",
    lastName: "Davis",
    email: "emily.davis@example.com",
    position: "UI/UX Designer",
    phone: "+1 (555) 345-6789",
    userType: "user",
    role: "account",
    status: "pending",
    avatarUrl: "https://randomuser.me/api/portraits/women/36.jpg",
    department: "Design",
    hireDate: "August 12, 2022",
    lastActive: "1 hour ago",
  },
  {
    id: "5",
    firstName: "James",
    lastName: "Brown",
    email: "james.brown@example.com",
    position: "QA Analyst",
    phone: "+1 (555) 456-7890",
    userType: "user",
    role: "support",
    status: "registered",
    avatarUrl: "https://randomuser.me/api/portraits/men/56.jpg",
    department: "Quality Assurance",
    hireDate: "April 9, 2023",
    lastActive: "10 minutes ago",
  },
  {
    id: "6",
    firstName: "Olivia",
    lastName: "Martinez",
    email: "olivia.martinez@example.com",
    position: "Marketing Manager",
    phone: "+1 (555) 567-8901",
    userType: "admin",
    role: "hr",
    status: "rejected",
    avatarUrl: "https://randomuser.me/api/portraits/women/52.jpg",
    department: "Marketing",
    hireDate: "February 18, 2020",
    lastActive: "3 hours ago",
  },
  {
    id: "7",
    firstName: "Robert",
    lastName: "Miller",
    email: "robert.miller@example.com",
    position: "DevOps Engineer",
    phone: "+1 (555) 678-9012",
    userType: "user",
    role: "developer",
    status: "registered",
    avatarUrl: "https://randomuser.me/api/portraits/men/61.jpg",
    department: "Infrastructure",
    hireDate: "November 3, 2018",
    lastActive: "15 minutes ago",
  },
  {
    id: "8",
    firstName: "Sophia",
    lastName: "Garcia",
    email: "sophia.garcia@example.com",
    position: "Business Analyst",
    phone: "+1 (555) 789-0123",
    userType: "user",
    role: "account",
    status: "registered",
    avatarUrl: "https://randomuser.me/api/portraits/women/60.jpg",
    department: "Business Analysis",
    hireDate: "July 7, 2021",
    lastActive: "4 hours ago",
  },
  {
    id: "9",
    firstName: "Daniel",
    lastName: "Anderson",
    email: "daniel.anderson@example.com",
    position: "Product Owner",
    phone: "+1 (555) 890-1234",
    userType: "admin",
    role: "support",
    status: "registered",
    avatarUrl: "https://randomuser.me/api/portraits/men/33.jpg",
    department: "Product",
    hireDate: "October 1, 2017",
    lastActive: "1 day ago",
  },
  {
    id: "10",
    firstName: "Grace",
    lastName: "Lee",
    email: "grace.lee@example.com",
    position: "Content Strategist",
    phone: "+1 (555) 901-2345",
    userType: "user",
    role: "developer",
    status: "pending",
    avatarUrl: "https://randomuser.me/api/portraits/women/25.jpg",
    department: "Content",
    hireDate: "May 10, 2024",
    lastActive: "just now",
  },
];
